skip_branch_with_pr: true

environment:
  GO_VERSION: 1.15.3
  GITHUB_TOKEN:
    secure: eiUu4bDjW+iunm/q1LsDOIBF3EOAZBRynjMztjPDwFOTDivVlYlSPvfjlQY3+Qd9

  matrix:
    # - job_name: Windows
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

matrix:
  fast_finish: true
  
for:
  
# ======================================
#      Windows
# ======================================

-
  matrix:
    only:
    - job_name: Windows

  init:
  - go version
  - echo %GOPATH%

  build_script:
  - go install github.com/pglet/pglet/cmd/pglet
  - dir %USERPROFILE%\Go\bin

  test_script:
  - run-tests.cmd

# ======================================
#      Linux
# ======================================

-
  matrix:
    only:
    - job_name: Linux

  install:
  - ./install_go.sh
  - sh: |
      sudo snap install --classic goreleaser
      goreleaser --version

  build_script:
  - go install github.com/pglet/pglet/cmd/pglet
  - ls $GOPATH/bin

  test_script:
  - ./run-tests.sh

  after_test:
  - sh: |
      if [[ "$APPVEYOR_REPO_TAG" == "true" ]]; then
        goreleaser
      else
        goreleaser --snapshot --skip-publish
      fi

  artifacts:
  - path: dist/pglet-*